In [1]:
import numpy as np

In [2]:
n = np.arange(27) #one-dimensional array

In [3]:
n.reshape(3, 9) #two-dimensional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
n.reshape(3,3,3) #three-dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
m = np.asarray([[234,456,789], [], []])

In [6]:
m

array([list([234, 456, 789]), list([]), list([])], dtype=object)

In [7]:
import cv2

In [8]:
img = cv2.imread("smallgray.png", 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
img2 = cv2.imread("smallgray.png", 1)
img2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
cv2.imwrite("newsmallgray.png", img2)

True

In [11]:
img[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [14]:
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [15]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
img2[0]

array([[187, 187, 187],
       [158, 158, 158],
       [104, 104, 104],
       [121, 121, 121],
       [143, 143, 143]], dtype=uint8)

In [24]:
img2[0, 1,2]

158

In [25]:
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [29]:
for i in img2:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [32]:
for i in range(len(img)):
    for j in img[i]:
        print(j)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [33]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [36]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [37]:
img_tuple = (img, img, img)
ims = np.hstack(img_tuple)

In [38]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [39]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [40]:
ims2 = np.vstack(img_tuple)

In [42]:
print(ims2)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [44]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [48]:
splt = np.hsplit(img, 5)

In [57]:
splt

[array([[187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182]], dtype=uint8)]

In [49]:
splt

[array([[187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182]], dtype=uint8)]

In [51]:
splt[0]

array([[187],
       [198],
       [209]], dtype=uint8)

In [52]:
splt2 = np.vsplit(img, 3)

In [53]:
splt2

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]

In [56]:
splt2[0]

array([[187, 158, 104, 121, 143]], dtype=uint8)